// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.obd_app

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object ObdApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** En qué está la conexión entre este celular y el ESP32 de un auto. */
enum class EstadoConexion(val raw: Int) {
  /** El ESP32 no está al alcance (auto apagado o lejos) y no hay ningún viaje abierto. */
  DESCONECTADO(0),
  /** Android detectó el ESP32, pero todavía no llegó ningún dato. */
  CONECTANDO(1),
  /** Están llegando datos. */
  CONECTADO(2),
  /**
   * Se cortó la conexión con un viaje abierto y todavía corre el tiempo de gracia: si
   * vuelve a tiempo el viaje sigue; si no, se cierra.
   */
  RECONECTANDO(3);

  companion object {
    fun ofRaw(raw: Int): EstadoConexion? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TelemetryEvent (
  val speed: Long? = null,
  val rpm: Long? = null,
  val fuel: Long? = null,
  val lat: Double? = null,
  val lng: Double? = null,
  /**
   * Auto del que vienen los datos (sale de la MAC del ESP32). Null si ese ESP32 no está
   * vinculado a ningún auto en este celular.
   */
  val carId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TelemetryEvent {
      val speed = pigeonVar_list[0] as Long?
      val rpm = pigeonVar_list[1] as Long?
      val fuel = pigeonVar_list[2] as Long?
      val lat = pigeonVar_list[3] as Double?
      val lng = pigeonVar_list[4] as Double?
      val carId = pigeonVar_list[5] as String?
      return TelemetryEvent(speed, rpm, fuel, lat, lng, carId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      speed,
      rpm,
      fuel,
      lat,
      lng,
      carId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TelemetryEvent
    return ObdApiPigeonUtils.deepEquals(this.speed, other.speed) && ObdApiPigeonUtils.deepEquals(this.rpm, other.rpm) && ObdApiPigeonUtils.deepEquals(this.fuel, other.fuel) && ObdApiPigeonUtils.deepEquals(this.lat, other.lat) && ObdApiPigeonUtils.deepEquals(this.lng, other.lng) && ObdApiPigeonUtils.deepEquals(this.carId, other.carId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ObdApiPigeonUtils.deepHash(this.speed)
    result = 31 * result + ObdApiPigeonUtils.deepHash(this.rpm)
    result = 31 * result + ObdApiPigeonUtils.deepHash(this.fuel)
    result = 31 * result + ObdApiPigeonUtils.deepHash(this.lat)
    result = 31 * result + ObdApiPigeonUtils.deepHash(this.lng)
    result = 31 * result + ObdApiPigeonUtils.deepHash(this.carId)
    return result
  }
  override fun toString(): String {
    return "TelemetryEvent(speed=$speed, rpm=$rpm, fuel=$fuel, lat=$lat, lng=$lng, carId=$carId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectionEvent (
  val carId: String,
  val estado: EstadoConexion,
  /**
   * Solo con [EstadoConexion.reconectando]: momento (epoch en ms) en que vence el tiempo
   * de gracia y el viaje se da por terminado si no volvió la conexión.
   */
  val finGraciaMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionEvent {
      val carId = pigeonVar_list[0] as String
      val estado = pigeonVar_list[1] as EstadoConexion
      val finGraciaMs = pigeonVar_list[2] as Long?
      return ConnectionEvent(carId, estado, finGraciaMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      carId,
      estado,
      finGraciaMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectionEvent
    return ObdApiPigeonUtils.deepEquals(this.carId, other.carId) && ObdApiPigeonUtils.deepEquals(this.estado, other.estado) && ObdApiPigeonUtils.deepEquals(this.finGraciaMs, other.finGraciaMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ObdApiPigeonUtils.deepHash(this.carId)
    result = 31 * result + ObdApiPigeonUtils.deepHash(this.estado)
    result = 31 * result + ObdApiPigeonUtils.deepHash(this.finGraciaMs)
    return result
  }
  override fun toString(): String {
    return "ConnectionEvent(carId=$carId, estado=$estado, finGraciaMs=$finGraciaMs)"
  }
}
private open class ObdApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EstadoConexion.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TelemetryEvent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EstadoConexion -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is TelemetryEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ConnectionEvent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class ObdFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ObdFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ObdApiPigeonCodec()
    }
  }
  suspend fun onTelemetryUpdated(eventArg: TelemetryEvent)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.obd_app.ObdFlutterApi.onTelemetryUpdated$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(ObdApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /** Cambió el estado de la conexión con el ESP32 de un auto. */
  suspend fun onConnectionChanged(eventArg: ConnectionEvent)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.obd_app.ObdFlutterApi.onConnectionChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(ObdApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
