// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
import Flutter

extension FlutterError: Error {}

struct TelemetryEvent {
  var speed: Int64? = nil
  var rpm: Int64? = nil
  var fuel: Int64? = nil
  var lat: Double? = nil
  var lng: Double? = nil

  static func fromList(_ list: [Any?]) -> TelemetryEvent? {
    let speed: Int64? = list[0] is NSNull ? nil : (list[0] is Int64? ? list[0] as! Int64? : Int64(list[0] as! Int32))
    let rpm: Int64? = list[1] is NSNull ? nil : (list[1] is Int64? ? list[1] as! Int64? : Int64(list[1] as! Int32))
    let fuel: Int64? = list[2] is NSNull ? nil : (list[2] is Int64? ? list[2] as! Int64? : Int64(list[2] as! Int32))
    let lat: Double? = list[3] as? Double
    let lng: Double? = list[4] as? Double

    return TelemetryEvent(
      speed: speed,
      rpm: rpm,
      fuel: fuel,
      lat: lat,
      lng: lng
    )
  }
  func toList() -> [Any?] {
    return [
      speed,
      rpm,
      fuel,
      lat,
      lng,
    ]
  }
}

private class ObdApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return TelemetryEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ObdApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TelemetryEvent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ObdApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ObdApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ObdApiPigeonCodecWriter(data: data)
  }
}

class ObdApiPigeonCodec: FlutterStandardMessageCodec {
  static let shared = ObdApiPigeonCodec(readerWriter: ObdApiPigeonCodecReaderWriter())
}

class ObdFlutterApi {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  func onTelemetryUpdated(eventArg eventArgArg: TelemetryEvent, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.obd_app.ObdFlutterApi.onTelemetryUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: ObdApiPigeonCodec.shared)
    channel.sendMessage([eventArgArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(FlutterError(code: "channel-error", message: "Unable to establish connection on channel.", details: "")))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = listResponse[1] as? String
        let details: String? = listResponse[2] as? String
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}